spring.datasource.url=jdbc:mysql://heladosbased123.mysql.database.azure.com:3306/heladeria?useSSL=true&requireSSL=true&serverTimezone=UTC
spring.datasource.username=heladeriamysqldb
spring.datasource.password=Brayan1213
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Pool
spring.datasource.hikari.maximum-pool-size=5
spring.datasource.hikari.connection-timeout=5000
spring.datasource.hikari.initialization-fail-timeout=0

# JPA

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

# Puerto Azure
server.port=${PORT:8080}

# Gemini

gemini.api.key=${GEMINI_API_KEY}
gemini.api.url=https://generativelanguage.googleapis.com/v1beta/models/gemini-1.5-flash:generateContent
gemini.historial.maxMensajes=30

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=brayandjesus020@gmail.com
spring.mail.password=nryecrekqsbmqldl
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
